### PR TITLE
Payment gateway intregration native

### PR DESCRIPTION
**Pull request by theoctober19th**
Moved this PR  here: https://github.com/logblythe/astrologer_v2/pull/8

@gurungsunil's comment:

> Note : I have added new field in user model country iso so new field country iso need to be added to api.
> Note : For ios project only run on physical device because ios contain only physical device esewa framework and testing needed for ios.
> -Integrate native esewa payment for android ios.
> -Navigate to homepage when user profile updated successfully.
> -Added choose able country dropdown.
> -Handle permission issue while uploading image.
> -Integrate native date picker for android only (pick by scrolling).
> -change in sqflite version from (2 to 3) to add new column country iso.
> -some minor changes.

### CODE REVIEW

**Comment by theoctober19th** [comment]
Hi  @gurungsunil, I have moved the PR here. I'm not familiar with the Flutter code, so, let's add a few reviewers. I'll add one of my friend. Feel free to add if you have someone in mind.

**Comment by theoctober19th** [comment]
@getrajan could you briefly peer review the code before I merge it?

**Comment by theoctober19th** [comment]
> Note : I have added new field in user model country iso so new field country iso need to be added to api.

@gurungsunil, do you mean that the change is required on the REST API side? If so, that needs to be requested to Sijan too. In the meanwhile, will the code break until that change is incorporated in REST API, or will it work?

>Note : For ios project only run on physical device because ios contain only physical device esewa framework and testing needed for ios.

Could you please elaborate this point a bit clearly? Since the project is already checked on a physical device, what else is needed to be tested here?

**Comment by gurungsunil** [comment]
@theoctober19th  actually esewa has two type of framework one for simulator and another for physical devices (for deployment), i have integrated physical device framework cuz simulator framework has some versioning issue so due to framework it won't run on simulator.

**Comment by theoctober19th** [comment]
@gurungsunil In that case, since it is already tested on a physical device, we can safely release this to TestFlight, right?

**Comment by gurungsunil** [comment]
@theoctober19th no i haven't tested on physical device. I simply implement code only . i am having profiling issue while trying test. I need to import developer profile in automatic sign in. code wont compile until i maintain automatic sign in.

**Comment by theoctober19th** [comment]
@gurungsunil Well, in that case, let me make a build once the PR gets merged, and then let's test that build. Will also release to TestFlight, so that we can beta test within ourselves.

**Review by getrajan — APPROVED** [review]
there's constant price Rs. 1, Is this right? 
Overall other is fine

**Comment by gurungsunil** [comment]
@getrajan actually that's for test purpose it will be change when we are going to deploy the app in production.

**Comment by theoctober19th** [comment]
@gurungsunil Got it. It would be better if we could dynamically change that amount once we go to production, rather than hardcoding it, right?

**Pull request merged**
